using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace TEST_FINGER
{
    public partial class Form1 : Form
    {
        VanTayEntities dbContext = new VanTayEntities();
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            //        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //        dbContext.FP_DanhMucMayQuetVanTay.LoadAsync().ContinueWith(loadTask =>
            //        {
            //// Bind data to control when loading complete
            //fP_DanhMucMayQuetVanTayBindingSource.DataSource = dbContext.FP_DanhMucMayQuetVanTay.Local.ToBindingList();
            //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            gridControl1.DataSource = fP_DanhMucMayQuetVanTayBindingSource;
        }

        private void btnluu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            fP_DanhMucMayQuetVanTayBindingSource.EndEdit();
            dbContext.SaveChanges();
        }

        private void btnload_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowPrintPreview();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            dbContext.FP_DanhMucMayQuetVanTay.Load();
            fP_DanhMucMayQuetVanTayBindingSource.DataSource = dbContext.FP_DanhMucMayQuetVanTay.Local;
        }
    }
}
