//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST_FINGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_DanhMucMayQuetVanTay
    {
        public int Id { get; set; }
        public string TenMay { get; set; }
        public string MoTaViTri { get; set; }
        public string VaoRa { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> TinhTrangSuDung { get; set; }
        public Nullable<bool> DKVanTay { get; set; }
    }
}
